INSERT INTO db_ricette.recipes(title, photoUrL, ingredients, portions, preparation_time, recipe_text)VALUES('Risotto allo Zafferano', 'https://www.giallozafferano.it/images/ricette/174/17481/foto_hd/hd650x433_wm.jpg', 'Zafferano in pistilli 1 cucchiaino, Riso Carnaroli 320g, Burro 125g, Cipolle 1, Grana Padano DOP da grattugiare 80g, Vino bianco 40g, Acqua q.b., Brodo vegetale 1l, Sale fino q.b.', 4, 25, "Per preparare il risotto allo zafferano, metti i pistilli in acqua per la notte. Prepara un litro di brodo vegetale. Trita la cipolla e stufala in burro. Aggiungi il riso e tostalo, sfuma con il vino e cuoci per 18-20 minuti, aggiungendo brodo gradualmente. A 5 minuti dalla fine, aggiungi l'acqua con lo zafferano. Spegni, salta, manteca con formaggio e burro. Lascia riposare e servi con pistilli." );
INSERT INTO db_ricette.recipes(title, photoUrL, ingredients, portions, preparation_time, recipe_text)VALUES('Spaghetti Cacio e Pepe', 'https://www.giallozafferano.it/images/219-21989/Spaghetti-Cacio-e-Pepe_450x300.jpg', 'Spaghetti 320g, Pecorino romano stagionatura media, da grattugiare 200g, Pepe nero in grani 5g', 4, 15, "Per gli spaghetti cacio e pepe, riempite una pentola con metà dell'acqua solita per rendere più ricco di amido. Grattugiate il Pecorino e mettetene da parte. Cuocete gli spaghetti, poi tostate il pepe in padella con acqua di cottura. Scolate gli spaghetti, risottateli con il pepe e il Pecorino. Aggiungete la crema di Pecorino grattugiato con acqua di cottura. Servite con Pecorino e pepe." );
INSERT INTO db_ricette.recipes(title, photoUrL, ingredients, portions, preparation_time, recipe_text)VALUES('Spaghetti Alla Nerano', 'https://www.giallozafferano.it/images/232-23249/Spaghetti-alla-Nerano_450x300.jpg', "Spaghetti 320g, Provolone del Monaco 150g, Zucchine 700g, Basilico q.b., Parmigiano Reggiano DOP da grattugiare 30g, Sale fino q.b., Pepe nero q.b., Aglio 1 spicchio, Olio extravergine d'oliva 30g", 4, 20, "Per gli spaghetti alla Nerano, tagliate sottilmente le zucchine e friggetele nell'olio a 150°C fino a doratura. Scolatele e conditele con sale e basilico. Cuocete gli spaghetti al dente, poi saltateli in una padella con olio, aglio, zucchine fritte, formaggio e acqua di cottura. Servite caldi con pepe." );
INSERT INTO db_ricette.recipes(title, photoUrL, ingredients, portions, preparation_time, recipe_text)VALUES('Arrosto di Vitello al forno con patate', 'https://www.giallozafferano.it/images/172-17292/Arrosto-di-vitello-al-forno-con-patate_450x300.jpg', "Sottofesa di vitello 600g, Patate 1kg, Vino bianco 50g, Rosmarino 2 rametti, Aglio 2 spicchi, Olio extravergine d'oliva 40g, Sale fino q.b., Pepe nero q.b.", 4, 60, "Per l'arrosto di vitello al forno con patate, tagliate le patate a tocchetti, conditele con olio, sale, pepe, aglio e rosmarino, e cuocetele in forno a 200°C per 20 minuti. Nel frattempo, pulite e legate il pezzo di carne. Sigillate la carne in una padella con olio e vino bianco, quindi trasferitela sulla leccarda con le patate. Cuocete a 200°C fino a 65°C al centro della carne (circa 35 minuti). Lasciate riposare prima di affettare." );


INSERT INTO db_ricette.categories(name)VALUES('Antipasto');
INSERT INTO db_ricette.categories(name)VALUES('Primo piatto');
INSERT INTO db_ricette.categories(name)VALUES('Secondo piatto');
INSERT INTO db_ricette.categories(name)VALUES('Dessert');